name: 'La Balise Apartment '
favicon: null
layout_spectrum: 0.044780979165807366
typography_spectrum: 0.25114186271093786
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1ebe8'
    - '#7cbde6'
    - '#5a7ba0'
    - '#000600'
    - '#364120'
  brandStrength: 0.875
  lightness: 0.5689812612254173
  saturation: 0.125
  rhythmicContrast: 0.898191781481728
purpose: []
